/**
 * Cleanup: Delete fake reports generated by seed-consensus-boost.ts
 *
 * Identification criteria:
 * - quality_tier = 'reported' AND source = 'manual' AND import_source IS NULL
 * - notes match the fake note templates
 * - user_id is set (real users impersonated)
 *
 * Run: cd /home/ubuntu/handhelddb && npx tsx scripts/cleanup-fake-reports.ts
 */
import 'dotenv/config';
import { createClient } from '@supabase/supabase-js';

const supabase = createClient(
  process.env.SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_KEY!,
  { auth: { persistSession: false } },
);

// Known fake note patterns from seed-consensus-boost.ts
const FAKE_NOTE_PATTERNS = [
  'Runs great, no issues at all.',
  'Buttery smooth. Very happy with this.',
  'Perfect handheld experience.',
  'with no drops. Amazing.',
  'Zero complaints. Just works.',
  'Flawless. My go-to game on the go.',
  'Steady framerate, no stutters.',
  'Really surprised how well this runs.',
  'Solid performance overall. Minor dips occasionally.',
  'Very playable. Had to tweak a couple settings.',
  'Good experience, occasional stutter in busy scenes.',
  'Slight drops in heavy areas.',
  'Enjoyable. Not perfect but definitely good enough.',
  'Plays nicely once you find the right settings.',
  'for the most part.',
  'Playable but had to lower settings a lot.',
  'Needs some work to get stable. Worth it though.',
  'Decent at lower settings. Not ideal.',
  'but nothing higher.',
  'Struggles a bit but still enjoyable.',
  'Had to compromise on visuals for playability.',
  'Works but you gotta be patient with settings.',
  'Rough experience. Not really recommended.',
  'Barely playable even at lowest settings.',
  'Major frame drops. Not great.',
  'consistently.',
  'Below 30 most of the time. Disappointing.',
];

async function main() {
  console.log('=== Fake Report Cleanup ===\n');

  // Step 1: Count total reports
  const { count: totalCount } = await supabase
    .from('performance_reports')
    .select('id', { count: 'exact', head: true });
  console.log(`Total reports in DB: ${totalCount}`);

  // Step 2: Find suspected fake reports
  // Criteria: quality_tier='reported', source='manual', import_source IS NULL
  const allSuspect: any[] = [];
  let offset = 0;
  while (true) {
    const { data, error } = await supabase
      .from('performance_reports')
      .select('id, notes, quality_tier, source, import_source, import_source_id, user_id, created_at, fps_avg')
      .eq('quality_tier', 'reported')
      .eq('source', 'manual')
      .is('import_source', null)
      .range(offset, offset + 999);

    if (error) {
      console.error('Query error:', error.message);
      break;
    }
    if (!data || data.length === 0) break;
    allSuspect.push(...data);
    if (data.length < 1000) break;
    offset += 1000;
  }

  console.log(`Suspected fake reports (reported + manual + no import_source): ${allSuspect.length}`);

  // Step 3: Match against known fake note patterns
  const confirmed: string[] = [];
  const uncertain: string[] = [];

  for (const report of allSuspect) {
    const notes = (report.notes ?? '').trim();
    const isFakeNote = FAKE_NOTE_PATTERNS.some(pattern => notes.includes(pattern));

    if (isFakeNote) {
      confirmed.push(report.id);
    } else if (notes === '' || notes.length < 60) {
      // Short/empty notes from manual source with no import = suspicious
      uncertain.push(report.id);
    }
  }

  console.log(`Confirmed fake (matching note patterns): ${confirmed.length}`);
  console.log(`Uncertain (short/empty notes, manual, no import): ${uncertain.length}`);
  console.log('');

  // Also check: reports with import_source_id IS NULL and source='manual'
  // that have fake-sounding patterns
  const { data: alsoSuspect } = await supabase
    .from('performance_reports')
    .select('id, notes, quality_tier, source, import_source_id')
    .eq('source', 'manual')
    .is('import_source_id', null)
    .neq('quality_tier', 'ai_estimated')
    .limit(2000);

  const alsoFake = (alsoSuspect ?? []).filter(r => {
    const notes = (r.notes ?? '').trim();
    return FAKE_NOTE_PATTERNS.some(p => notes.includes(p));
  });
  console.log(`Additional fakes found (no import_source_id): ${alsoFake.length}`);

  // Merge all confirmed IDs
  const allFakeIds = [...new Set([...confirmed, ...alsoFake.map(r => r.id)])];
  console.log(`\nTotal confirmed fake reports to delete: ${allFakeIds.length}`);

  if (allFakeIds.length === 0) {
    console.log('No fake reports found. Database may already be clean.');
    return;
  }

  // Step 4: Delete in batches
  console.log('\nDeleting fake reports...');
  let deleted = 0;
  for (let i = 0; i < allFakeIds.length; i += 100) {
    const batch = allFakeIds.slice(i, i + 100);
    const { error: delErr } = await supabase
      .from('performance_reports')
      .delete()
      .in('id', batch);

    if (delErr) {
      console.error(`  Batch ${Math.floor(i / 100) + 1} failed:`, delErr.message);
    } else {
      deleted += batch.length;
      console.log(`  Deleted batch ${Math.floor(i / 100) + 1}: ${batch.length} (total: ${deleted})`);
    }
  }

  // Step 5: Final count
  const { count: finalCount } = await supabase
    .from('performance_reports')
    .select('id', { count: 'exact', head: true });
  console.log(`\nFinal report count: ${finalCount} (was ${totalCount}, removed ${deleted})`);

  // Step 6: Count remaining by quality tier
  for (const tier of ['verified', 'community_confirmed', 'reported', 'ai_estimated', 'imported']) {
    const { count } = await supabase
      .from('performance_reports')
      .select('id', { count: 'exact', head: true })
      .eq('quality_tier', tier);
    console.log(`  ${tier}: ${count}`);
  }
}

main().catch(console.error);
