import { createClient } from '@supabase/supabase-js';
import 'dotenv/config';

const supabase = createClient(
  process.env.SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_KEY!,
);

const DEVICES = [
  {
    name: 'Steam Deck OLED',
    slug: 'steam-deck-oled',
    manufacturer: 'Valve',
    chip: 'AMD Van Gogh (custom APU)',
    gpu: 'RDNA 2, 8 CUs @ 1.6 GHz',
    ram_gb: 16,
    storage_gb: 512,
    screen_resolution: '1280x800',
    screen_size: 7.4,
    screen_type: 'HDR OLED',
    battery_wh: 50,
    tdp_min: 3,
    tdp_max: 15,
    tdp_default: 12,
    weight_grams: 640,
    default_os: 'SteamOS 3.6',
    supports_windows: true,
    msrp_usd: 549,
    chipset_generation: 'RDNA 2',
    form_factor: 'slab',
    release_date: '2023-11-16',
    is_active: true,
  },
  {
    name: 'Steam Deck LCD',
    slug: 'steam-deck-lcd',
    manufacturer: 'Valve',
    chip: 'AMD Van Gogh (custom APU)',
    gpu: 'RDNA 2, 8 CUs @ 1.6 GHz',
    ram_gb: 16,
    storage_gb: 256,
    screen_resolution: '1280x800',
    screen_size: 7.0,
    screen_type: 'IPS LCD',
    battery_wh: 40,
    tdp_min: 3,
    tdp_max: 15,
    tdp_default: 12,
    weight_grams: 669,
    default_os: 'SteamOS 3.5',
    supports_windows: true,
    msrp_usd: 399,
    chipset_generation: 'RDNA 2',
    form_factor: 'slab',
    release_date: '2022-02-25',
    is_active: true,
  },
  {
    name: 'ASUS ROG Ally X',
    slug: 'rog-ally-x',
    manufacturer: 'ASUS',
    chip: 'AMD Ryzen Z1 Extreme',
    gpu: 'RDNA 3, 12 CUs @ 2.7 GHz',
    ram_gb: 24,
    storage_gb: 1024,
    screen_resolution: '1920x1080',
    screen_size: 7.0,
    screen_type: 'IPS',
    battery_wh: 80,
    tdp_min: 9,
    tdp_max: 30,
    tdp_default: 17,
    weight_grams: 678,
    default_os: 'Windows 11',
    supports_windows: true,
    msrp_usd: 799,
    chipset_generation: 'RDNA 3',
    form_factor: 'slab',
    release_date: '2024-07-22',
    is_active: true,
  },
  {
    name: 'ASUS ROG Ally',
    slug: 'rog-ally',
    manufacturer: 'ASUS',
    chip: 'AMD Ryzen Z1 Extreme',
    gpu: 'RDNA 3, 12 CUs @ 2.7 GHz',
    ram_gb: 16,
    storage_gb: 512,
    screen_resolution: '1920x1080',
    screen_size: 7.0,
    screen_type: 'IPS',
    battery_wh: 40,
    tdp_min: 9,
    tdp_max: 30,
    tdp_default: 15,
    weight_grams: 608,
    default_os: 'Windows 11',
    supports_windows: true,
    msrp_usd: 699,
    chipset_generation: 'RDNA 3',
    form_factor: 'slab',
    release_date: '2023-06-13',
    is_active: true,
  },
  {
    name: 'Lenovo Legion Go',
    slug: 'legion-go',
    manufacturer: 'Lenovo',
    chip: 'AMD Ryzen Z1 Extreme',
    gpu: 'RDNA 3, 12 CUs @ 2.7 GHz',
    ram_gb: 16,
    storage_gb: 512,
    screen_resolution: '2560x1600',
    screen_size: 8.8,
    screen_type: 'IPS',
    battery_wh: 49.2,
    tdp_min: 8,
    tdp_max: 30,
    tdp_default: 20,
    weight_grams: 854,
    default_os: 'Windows 11',
    supports_windows: true,
    msrp_usd: 699,
    chipset_generation: 'RDNA 3',
    form_factor: 'slab',
    release_date: '2023-10-31',
    is_active: true,
  },
  {
    name: 'Lenovo Legion Go S',
    slug: 'legion-go-s',
    manufacturer: 'Lenovo',
    chip: 'AMD Ryzen Z2 Go',
    gpu: 'RDNA 3.5, 12 CUs',
    ram_gb: 16,
    storage_gb: 512,
    screen_resolution: '1920x1200',
    screen_size: 8.0,
    screen_type: 'IPS',
    battery_wh: 55.5,
    tdp_min: 8,
    tdp_max: 30,
    tdp_default: 15,
    weight_grams: 730,
    default_os: 'SteamOS',
    supports_windows: true,
    msrp_usd: 499,
    chipset_generation: 'RDNA 3.5',
    form_factor: 'slab',
    release_date: '2025-01-09',
    is_active: true,
  },
  {
    name: 'MSI Claw 8 AI+',
    slug: 'msi-claw-8-ai-plus',
    manufacturer: 'MSI',
    chip: 'Intel Core Ultra 7 258V',
    gpu: 'Intel Arc 140V',
    ram_gb: 32,
    storage_gb: 1024,
    screen_resolution: '1920x1200',
    screen_size: 8.0,
    screen_type: 'IPS',
    battery_wh: 80,
    tdp_min: 10,
    tdp_max: 37,
    tdp_default: 20,
    weight_grams: 795,
    default_os: 'Windows 11',
    supports_windows: true,
    msrp_usd: 899,
    chipset_generation: 'Xe2',
    form_factor: 'slab',
    release_date: '2025-01-06',
    is_active: true,
  },
  {
    name: 'Ayaneo 2S',
    slug: 'ayaneo-2s',
    manufacturer: 'Ayaneo',
    chip: 'AMD Ryzen 7 7840U',
    gpu: 'RDNA 3, 12 CUs @ 2.7 GHz',
    ram_gb: 16,
    storage_gb: 512,
    screen_resolution: '1920x1200',
    screen_size: 7.0,
    screen_type: 'IPS',
    battery_wh: 50.25,
    tdp_min: 5,
    tdp_max: 33,
    tdp_default: 15,
    weight_grams: 680,
    default_os: 'Windows 11',
    supports_windows: true,
    msrp_usd: 799,
    chipset_generation: 'RDNA 3',
    form_factor: 'slab',
    release_date: '2023-09-25',
    is_active: true,
  },
  {
    name: 'GPD Win 4',
    slug: 'gpd-win-4',
    manufacturer: 'GPD',
    chip: 'AMD Ryzen 7 7840U',
    gpu: 'RDNA 3, 12 CUs @ 2.7 GHz',
    ram_gb: 32,
    storage_gb: 512,
    screen_resolution: '1920x1080',
    screen_size: 6.0,
    screen_type: 'IPS',
    battery_wh: 45.62,
    tdp_min: 5,
    tdp_max: 28,
    tdp_default: 15,
    weight_grams: 598,
    default_os: 'Windows 11',
    supports_windows: true,
    msrp_usd: 799,
    chipset_generation: 'RDNA 3',
    form_factor: 'slider',
    release_date: '2024-01-15',
    is_active: true,
  },
  {
    name: 'Nintendo Switch 2',
    slug: 'nintendo-switch-2',
    manufacturer: 'Nintendo',
    chip: 'NVIDIA T239 (custom Tegra)',
    gpu: 'Ampere, 12 SMs',
    ram_gb: 12,
    storage_gb: 256,
    screen_resolution: '1920x1080',
    screen_size: 7.9,
    screen_type: 'LCD',
    battery_wh: 45,
    tdp_min: 5,
    tdp_max: 25,
    tdp_default: 15,
    weight_grams: 500,
    default_os: 'Nintendo OS',
    supports_windows: false,
    msrp_usd: 449,
    chipset_generation: 'Ampere',
    form_factor: 'slab',
    release_date: '2025-06-05',
    is_active: true,
  },
];

async function seed() {
  console.log('Seeding devices...');

  for (const device of DEVICES) {
    const { error } = await supabase
      .from('devices')
      .upsert(device, { onConflict: 'slug' });

    if (error) {
      console.error(`  Failed: ${device.name} — ${error.message}`);
    } else {
      console.log(`  Seeded: ${device.name}`);
    }
  }

  console.log(`Done! ${DEVICES.length} devices seeded.`);
  process.exit(0);
}

seed().catch((err) => {
  console.error('Seed failed:', err);
  process.exit(1);
});
